import{S as p,i as l,a as b}from"./assets/vendor-b42c18af.js";(function(){const a=document.createElement("link").relList;if(a&&a.supports&&a.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))n(r);new MutationObserver(r=>{for(const e of r)if(e.type==="childList")for(const i of e.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&n(i)}).observe(document,{childList:!0,subtree:!0});function t(r){const e={};return r.integrity&&(e.integrity=r.integrity),r.referrerPolicy&&(e.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?e.credentials="include":r.crossOrigin==="anonymous"?e.credentials="omit":e.credentials="same-origin",e}function n(r){if(r.ep)return;r.ep=!0;const e=t(r);fetch(r.href,e)}})();const s={formEl:document.querySelector('.js-search-form[data-id="1"]'),imageEl:document.querySelector(".js-image-container"),loadMoreBtn:document.querySelector(".load-more-btn"),loader:document.querySelector(".loader")};s.loader.style.display="none";function y(){s.loader.style.display="block"}function u(){s.loader.style.display="none"}async function h(o,a=1,t=15){const n="https://pixabay.com/api/",e=`?${new URLSearchParams({key:"42138103-4c7bc70fd41b029843ebe333e",q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:a,per_page:t})}`,i=n+e;try{return(await b.get(i)).data}catch(d){throw console.error("Error fetching images:",d),d}}function g(o,a=!0){const t=document.querySelector(".js-image-container");a&&(t.innerHTML="");const n=o.map(e=>`
      <a href="${e.largeImageURL}" class="lightbox">
        <div class="image-card">
          <img src="${e.webformatURL}" alt="${e.tags}">
          <span>Likes: ${e.likes}</span>
          <span>Views: ${e.views}</span>
          <span>Comments: ${e.comments}</span>
          <span>Downloads: ${e.downloads}</span>
        </div>
      </a>
    `).join("");a?t.innerHTML=n:t.insertAdjacentHTML("beforeend",n),L.refresh();const r=document.querySelector(".image-card").getBoundingClientRect().height;window.scrollBy({top:r*2,behavior:"smooth"})}const L=new p(".js-image-container  a",{captionsData:"alt",captionDelay:250});let m="",c=1;s.formEl.addEventListener("submit",async o=>{o.preventDefault(),y();const a=o.target.elements.query.value.trim();if(!a)return l.error({title:"Error",message:"Please enter a search query!"}),m="",c=1,s.loadMoreBtn.style.display="none",u();m=a,c=1;try{const t=await h(a);t.hits.length===0?l.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!"}):(g(t.hits),t.hits.length>=15&&(s.loadMoreBtn.style.display="block"))}catch(t){console.error(t),l.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!"})}finally{u()}});let f=!0;async function w(){try{if(!f)return;y(),c++;const o=await h(m,c);o.hits.length===0?(f=!1,s.loadMoreBtn.classList.add("disabled"),l.info({title:"Info",message:"We're sorry, but you've reached the end of search results."})):g(o.hits,!1)}catch(o){console.error(o),l.error({title:"Error",message:"Failed to load more images!"})}finally{u()}}s.loadMoreBtn.addEventListener("click",()=>{f&&w()});
//# sourceMappingURL=commonHelpers.js.map
