import{S as h,i as l,a as p}from"./assets/vendor-4a5fde41.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))a(r);new MutationObserver(r=>{for(const e of r)if(e.type==="childList")for(const i of e.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&a(i)}).observe(document,{childList:!0,subtree:!0});function t(r){const e={};return r.integrity&&(e.integrity=r.integrity),r.referrerPolicy&&(e.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?e.credentials="include":r.crossOrigin==="anonymous"?e.credentials="omit":e.credentials="same-origin",e}function a(r){if(r.ep)return;r.ep=!0;const e=t(r);fetch(r.href,e)}})();const c={formEl:document.querySelector('.js-search-form[data-id="1"]'),imageEl:document.querySelector(".js-image-container"),loadMoreBtn:document.querySelector(".load-more-btn")},n=document.querySelector(".loader");n.style.display="none";async function u(o,s=1,t=15){const a="https://pixabay.com/api/",e=`?${new URLSearchParams({key:"42138103-4c7bc70fd41b029843ebe333e",q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:s,per_Page:t})}`,i=a+e;try{return(await p.get(i)).data}catch(y){throw console.error(y),new Error("Error fetching images")}}function m(o,s=!0){const t=document.querySelector(".js-image-container");s&&(t.innerHTML="");const a=o.map(e=>`
      <a href="${e.largeImageURL}" class="lightbox">
        <div class="image-card">
          <img src="${e.webformatURL}" alt="${e.tags}">
          <span>Likes: ${e.likes}</span>
          <span>Views: ${e.views}</span>
          <span>Comments: ${e.comments}</span>
          <span>Downloads: ${e.downloads}</span>
        </div>
      </a>
    `).join("");s?t.innerHTML=a:t.insertAdjacentHTML("beforeend",a),n.style.display="none",g.refresh();const r=document.querySelector(".image-card").getBoundingClientRect().height;window.scrollBy({top:r*2,behavior:"smooth"})}const g=new h(".js-image-container  a",{captionsData:"alt",captionDelay:250});let f="",d=1;async function b(){try{d++;const o=await u(f,d);o.hits.length===0?(n.style.display="none",c.loadMoreBtn.style.display="none",l.info({title:"Info",message:"We're sorry, but you've reached the end of search results."})):m(o.hits,!1)}catch(o){console.error(o),l.error({title:"Error",message:"Failed to load more images!"})}}c.loadMoreBtn.addEventListener("click",b);c.formEl.addEventListener("submit",async o=>{o.preventDefault(),n.style.display="block";const s=o.target.elements.query.value.trim();if(!s){n.style.display="none",l.error({title:"Error",message:"Please enter a search query!"});return}f=s,d=1,c.loadMoreBtn.style.display="none";try{const t=await u(s);t.hits.length===0?(n.style.display="none",l.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!"})):(m(t.hits),t.hits.length>=15&&(c.loadMoreBtn.style.display="block"))}catch(t){console.error(t),l.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!"})}finally{n.style.display="none"}});
//# sourceMappingURL=commonHelpers.js.map
