import{S as b,i,a as L}from"./assets/vendor-b42c18af.js";(function(){const a=document.createElement("link").relList;if(a&&a.supports&&a.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))s(r);new MutationObserver(r=>{for(const e of r)if(e.type==="childList")for(const n of e.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&s(n)}).observe(document,{childList:!0,subtree:!0});function t(r){const e={};return r.integrity&&(e.integrity=r.integrity),r.referrerPolicy&&(e.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?e.credentials="include":r.crossOrigin==="anonymous"?e.credentials="omit":e.credentials="same-origin",e}function s(r){if(r.ep)return;r.ep=!0;const e=t(r);fetch(r.href,e)}})();const c={formEl:document.querySelector('.js-search-form[data-id="1"]'),imageEl:document.querySelector(".js-image-container"),loadMoreBtn:document.querySelector(".load-more-btn")},f=document.querySelector(".loader");f.style.display="none";function h(){f.style.display="block"}function d(){f.style.display="none"}async function g(o,a=1,t=15){const s="https://pixabay.com/api/",e=`?${new URLSearchParams({key:"42138103-4c7bc70fd41b029843ebe333e",q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:a,per_page:t})}`,n=s+e;try{return(await L.get(n)).data}catch(y){console.error("Error fetching images:",y)}}function p(o,a=!0){const t=document.querySelector(".js-image-container");a&&(t.innerHTML="");const s=o.map(e=>`
      <a href="${e.largeImageURL}" class="lightbox">
        <div class="image-card">
          <img src="${e.webformatURL}" alt="${e.tags}">
          <span>Likes: ${e.likes}</span>
          <span>Views: ${e.views}</span>
          <span>Comments: ${e.comments}</span>
          <span>Downloads: ${e.downloads}</span>
        </div>
      </a>
    `).join("");a?t.innerHTML=s:t.insertAdjacentHTML("beforeend",s),w.refresh();const r=document.querySelector(".image-card").getBoundingClientRect().height;window.scrollBy({top:r*2,behavior:"smooth"})}const w=new b(".js-image-container  a",{captionsData:"alt",captionDelay:250});let u="",l=1;c.formEl.addEventListener("submit",async o=>{o.preventDefault(),h();const a=o.target.elements.query.value.trim();if(!a)return i.error({title:"Error",message:"Please enter a search query!"}),u="",l=1,c.loadMoreBtn.style.display="none",d();u=a,l=1;try{const t=await g(a);t.hits.length===0?i.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!"}):(p(t.hits),t.hits.length>=15&&(c.loadMoreBtn.style.display="block"))}catch(t){console.error(t),i.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!"})}finally{d()}});let m=!0;async function E(){try{if(!m)return;h(),l++;const o=await g(u,l);o.hits.length===0?(m=!1,c.loadMoreBtn.classList.add("disabled"),i.info({title:"Info",message:"We're sorry, but you've reached the end of search results."})):p(o.hits,!1)}catch(o){console.error(o),i.error({title:"Error",message:"Failed to load more images!"})}finally{d()}}c.loadMoreBtn.addEventListener("click",()=>{m&&E()});
//# sourceMappingURL=commonHelpers.js.map
